# Generated by Django 4.0.4 on 2022-04-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxScoreHitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, null=True)),
                ('player_id', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('xwoba', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('xba', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('xiso', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('xobp', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('brl', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('brl_percent', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('exit_velocity', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('hard_hit_percent', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('k_percent', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('bb_percent', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('whiff_percent', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('sprint_speed', models.IntegerField(null=True)),
                ('oaa', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoxScorePitching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
